/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package socialnetwork;

import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Fahrettin
 */
public class kayitPanel extends javax.swing.JFrame {

    String pu = "socialNetworkPU";

    /**
     * Creates new form kayitPanel
     */
    public kayitPanel() {
        initComponents();
        int year = Calendar.getInstance().get(Calendar.YEAR);
        cmb_yil.removeAllItems();
        int yassiniri = 10;
        for (int i = 0; i < 80; i++) {
            cmb_yil.addItem(year - yassiniri - i);
        }
lbl_eposta.setText("");
    }

    public String generateUniqueFileName() {
        String DATE_FORMAT = "yyyyMMdd_HHmmss-SSS";
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat(DATE_FORMAT);
        Random nahcis = new Random();
        int sayi = nahcis.nextInt(9999);
        String uniqName = "i" + sdf.format(new Date()) + "_" + sayi;
        return uniqName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpCinsiyet = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_adi = new javax.swing.JTextField();
        txt_soyadi = new javax.swing.JTextField();
        txt_kullaniciAdi = new javax.swing.JTextField();
        txt_ePosta = new javax.swing.JTextField();
        cmb_ulke = new javax.swing.JComboBox();
        rd_E = new javax.swing.JRadioButton();
        rd_K = new javax.swing.JRadioButton();
        pTxt_sifre = new javax.swing.JPasswordField();
        pTxt_sifreOnayla = new javax.swing.JPasswordField();
        btn_gozat = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lbl_resim = new javax.swing.JLabel();
        lbl_eposta = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btn_kayitOl = new javax.swing.JButton();
        cmb_Gun = new javax.swing.JComboBox();
        cmb_ay = new javax.swing.JComboBox();
        cmb_yil = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Kayıt formunu eksiksiz doldurunuz.");

        jLabel2.setText("Ad");

        jLabel3.setText("Soyad");

        jLabel4.setText("Kullanıcı Adı");

        jLabel5.setText("Cinsiyet");

        jLabel6.setText("Şifre");

        jLabel7.setText("Şifreyi Onayla");

        jLabel8.setText("Doğum Tarihi");

        jLabel9.setText("E-Posta");

        jLabel10.setText("Ülke");

        txt_ePosta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_ePostaFocusLost(evt);
            }
        });

        cmb_ulke.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seçiniz..", "Almanya", "Amerika Birleşik Devletleri", "Angola", "Arjantin", "Arnavutluk", "Avustralya", "Avusturya", "Bangladeş", "Belçika", "Benin", "Beyaz Rusya", "Birleşik Arap Emirlikleri", "Bolivya", "Bosna ve Hersek", "Botswana", "Brezilya", "Bulgaristan", "Burkina Faso", "Burundi", "Cezayir", "Colombia", "Çad", "Çek Cumhuriyeti", "Çin", "Danimarka", "Dominik Cumhuriyeti", "Ekvador", "El Salvador", "Endonezya", "Eritre", "Ermenistan", "Estonya", "Etiyopya", "Fas", "Fiji", "Fildişi Sahili", "Filipinler", "Filistin Bölgesi", "Finlandiya", "Fransa", "forumdas.net", "Gabon", "Gambia", "Gana", "Georgia", "Gine", "Guatemala", "Güney Afrika", "Güney Kore", "Haiti", "Hırvatistan", "Hindistan", "Hollanda", "Honduras", "Hong Kong", "Irak", "İngiltere", "İran", "İrlanda", "İspanya", "İsrail", "İsveç", "İsviçre", "İtalya", "Jamaika", "Japonya", "Kamboçya", "Kamerun", "Kanada", "Kazakistan", "Kenya", "Kırgızistan", "Kongo", "Kosta Rika", "Kuveyt", "Kuzey Kore", "Küba", "Laos", "Lesotho", "Letonya", "Libya", "Litvanya", "Lübnan", "Macaristan", "Madagaskar", "Makedonya", "Malawi", "Malezya", "Mali", "Mauritius Adası", "Meksika", "Mısır", "Moğolistan", "Moldova", "Moritanya", "Mozambik", "Myanmar", "Namibia", "Nepal", "Nijer", "Nijerya", "Nikaragua", "Norveç", "Özbekistan", "Pakistan", "Panama", "Papua Yeni Gine", "Paraguay", "Peru", "Polonya", "Portekiz", "Porto Riko", "Romanya", "Ruanda", "Rusya", "Senegal", "Sırbistan", "Sierra Leone", "Singapur", "Slovakya", "Slovenya", "Somali", "Sri Lanka", "Sudan", "Suriye", "Suudi Arabistan", "Svaziland", "Şili", "Tacikistan", "Tanzanya", "Tayland", "Tayvan", "Togo", "Trinidad ve Tobago", "Tunus", "Türkiye", "Türkmenistan", "Uganda", "Ukrayna", "Umman", "Uruguay", "Ürdün", "Venezuela", "Vietnam", "Yemen", "Yeni Zelanda", "Yunanistan", "Zambiya", "Zimbabwe" }));

        grpCinsiyet.add(rd_E);
        rd_E.setSelected(true);
        rd_E.setText("Erkek");

        grpCinsiyet.add(rd_K);
        rd_K.setText("Kadın");

        btn_gozat.setText("Gözat...");
        btn_gozat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gozatActionPerformed(evt);
            }
        });

        jLabel11.setText(":");

        jLabel12.setText(":");

        jLabel13.setText(":");

        jLabel14.setText(":");

        jLabel15.setText(":");

        jLabel16.setText(":");

        jLabel17.setText(":");

        jLabel18.setText(":");

        jLabel19.setText(":");

        lbl_resim.setText("Resim Henüz Eklenmedi");
        lbl_resim.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_eposta.setText("label eposta hata");

        jLabel21.setText("Profil Resmi Ekle:");

        btn_kayitOl.setText("Kayıt Ol");
        btn_kayitOl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kayitOlActionPerformed(evt);
            }
        });

        cmb_Gun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cmb_ay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran", "Temmuz", "Ağustos", "Eylül", "Ekim", "Kasım", "Aralık" }));

        cmb_yil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_kullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmb_Gun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(cmb_ay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmb_yil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cmb_ulke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pTxt_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel14))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(68, 68, 68)
                                        .addComponent(jLabel11)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rd_E)
                                        .addGap(18, 18, 18)
                                        .addComponent(rd_K))
                                    .addComponent(pTxt_sifreOnayla, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ePosta, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_soyadi, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(lbl_eposta)))
                        .addContainerGap(74, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_resim, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_gozat)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_kayitOl)
                .addGap(319, 319, 319))
            .addGroup(layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_adi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)
                                .addComponent(jLabel3)
                                .addComponent(jLabel11)
                                .addComponent(txt_soyadi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(txt_kullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rd_K)
                                .addComponent(jLabel16)
                                .addComponent(rd_E)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(pTxt_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel13)
                                .addComponent(pTxt_sifreOnayla, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel17)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(txt_ePosta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel18)
                            .addComponent(cmb_Gun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_ay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_yil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cmb_ulke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(lbl_eposta)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(btn_gozat))
                    .addComponent(lbl_resim, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btn_kayitOl)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static BufferedImage scaleImage(BufferedImage image, int imageType,
            int newWidth, int newHeight) {
        // Make sure the aspect ratio is maintained, so the image is not distorted
        double thumbRatio = (double) newWidth / (double) newHeight;
        int imageWidth = image.getWidth(null);
        int imageHeight = image.getHeight(null);
        double aspectRatio = (double) imageWidth / (double) imageHeight;

        if (thumbRatio < aspectRatio) {
            newHeight = (int) (newWidth / aspectRatio);
        } else {
            newWidth = (int) (newHeight * aspectRatio);
        }

        // Draw the scaled image
        BufferedImage newImage = new BufferedImage(newWidth, newHeight,
                imageType);
        Graphics2D graphics2D = newImage.createGraphics();
        graphics2D.setRenderingHint(RenderingHints.KEY_INTERPOLATION,
                RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        graphics2D.drawImage(image, 0, 0, newWidth, newHeight, null);

        return newImage;
    }
    BufferedImage bi;
    String extension;
    boolean resim = false;
    private void btn_gozatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gozatActionPerformed
        // TODO add your handling code here:
        JFileChooser filechooser = new JFileChooser();
        filechooser.setDialogTitle("Lütfen Profil Resmini Seçiniz...");
        filechooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int returnval = filechooser.showOpenDialog(this);
        if (returnval == JFileChooser.APPROVE_OPTION) {
            File file = filechooser.getSelectedFile();
            String s = file.getAbsolutePath();
            String fname = s.substring(s.lastIndexOf(File.separator));
            extension = fname.substring(fname.indexOf("."));
            System.out.println(extension);
            if (".png".equals(extension) || ".jpg".equals(extension) || ".bmp".equals(extension) || ".jpeg".equals(extension)) {

                try {
                    bi = ImageIO.read(file);

                    lbl_resim.setIcon(new ImageIcon(scaleImage(bi, BufferedImage.TYPE_INT_RGB, lbl_resim.getWidth(), lbl_resim.getHeight())));
                    // File outputfile = new File("saved.png");
                    //ImageIO.write(bi, "png", outputfile);
                    resim = true;
                } catch (IOException e) {

                }
            } else {
                JOptionPane.showMessageDialog(null, "Seçtiğiniz resim dosyası png,jpg veya bmp olmalıdır. Lütfen tekrar deneyiniz.", "Hata", 0);
            }
            this.pack();


    }//GEN-LAST:event_btn_gozatActionPerformed
    }
    private void txt_ePostaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_ePostaFocusLost
        // TODO add your handling code here:
        if (!(lbl_eposta.getText()).equals(null)) {
            lbl_eposta.setText("");
        }
        emailKontrol ek = new emailKontrol();
        if (!ek.validate(txt_ePosta.getText())) {

            lbl_eposta.setText("Hatalı e-posta!");
        }

    }//GEN-LAST:event_txt_ePostaFocusLost

    private void btn_kayitOlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kayitOlActionPerformed
        // TODO add your handling code here:
        boolean kAdiKontrol = false;
        boolean mailKontrol = false;

        String dogumTarihi = cmb_Gun.getSelectedItem().toString() + "-" + (cmb_ay.getSelectedIndex() + 1) + "-" + cmb_yil.getSelectedItem().toString();

        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");

        if (cmb_ulke.getSelectedIndex() != 0 && !"".equals(txt_adi.getText()) && !"".equals(txt_ePosta.getText()) && !"".equals(txt_kullaniciAdi.getText()) && "".equals(lbl_eposta.getText()) && !"".equals(txt_soyadi.getText()) && !"".equals(dogumTarihi)) {
            if (pTxt_sifre.getText().equals(pTxt_sifreOnayla.getText())) {

                try {

                    int id = 1;//ilk kullanıcı için

                    KullaniciPK pk = new KullaniciPK();

                    pk.setKullaniciadi(txt_kullaniciAdi.getText());

                    Kullanici k = new Kullanici(pk);
                    k.setAdi(txt_adi.getText());
                    k.setSoyadi(txt_soyadi.getText());
                    k.setCinsiyet(rd_E.isSelected());
                    k.setEposta(txt_ePosta.getText());
                    k.setUlke(cmb_ulke.getSelectedItem().toString());
                    k.setSifre(pTxt_sifre.getText());
                    k.setDogumtarihi(dateFormat.parse(dogumTarihi));

                    EntityManagerFactory emf = Persistence.createEntityManagerFactory(pu);
                    EntityManager em = emf.createEntityManager();

                    Query q = em.createQuery("select c from Kullanici c");
                    List<Kullanici> klist = q.getResultList();
                    for (Kullanici kl : klist) {

                        if (txt_kullaniciAdi.getText() == null ? kl.kullaniciPK.getKullaniciadi() == null : txt_kullaniciAdi.getText().equals(kl.kullaniciPK.getKullaniciadi())) {
                            kAdiKontrol = true;

                        }
                        if (txt_ePosta.getText() == null ? kl.getEposta() == null : txt_ePosta.getText().equals(kl.getEposta())) {
                            mailKontrol = true;
                            System.out.println(mailKontrol);
                        }

                    }
                    Query qMaxId = em.createQuery("select MAX(c.kullaniciPK.id) from Kullanici c");
                    id = Integer.parseInt(qMaxId.getSingleResult().toString()) + 1;
                    pk.setId(id);
                    boolean bProfil = new File("photos" + File.separator + txt_kullaniciAdi.getText()).mkdir();
                    if (!kAdiKontrol && !mailKontrol) {
                        if (resim) {
                            String resimAdi = generateUniqueFileName();
                            //boolean bProfil = new File("photos" + File.separator + txt_kullaniciAdi.getText()).mkdir();
                            if (bProfil) {

                                File outputfile = new File("photos" + File.separator + txt_kullaniciAdi.getText() + File.separator + resimAdi + extension);
                                ImageIO.write(bi, extension.substring(extension.length() - 3, extension.length()), outputfile);

                            }
                            k.setProfilresmi(resimAdi + extension);
                        }
                        else k.setProfilresmi("no-image.png");
                        em.getTransaction().begin();
                        em.persist(k);
                        em.getTransaction().commit();

                        JOptionPane.showMessageDialog(null, "Kayıt oluşturuldu.");

                        em.close();
                        emf.close();
                        super.dispose();//pencere kapatıyorm

                    } else if (mailKontrol) {
                        JOptionPane.showMessageDialog(null, "Girmiş olduğunuz e-Posta adresi mevcut. Lütfen farklı bir e-Posta ile kayıt formunu doldurunuz.", "Mevcut Kullanıcı!", 0);
                    } else {
                        JOptionPane.showMessageDialog(null, "Girmiş olduğunuz kullanıcı adı mevcut. Lütfen farklı bir kullanıcı adı ile kayıt formunu doldurunuz.", "Mevcut Kullanıcı!", 0);
                    }
                } catch (Exception e) {
                    System.out.println(e);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Şifreler uyuşmuyor. Lütfen tekrar deneyiniz", "Şifre hatası!", 0);
                pTxt_sifre.setText("");
                pTxt_sifreOnayla.setText("");
            }
        } else {
            if (!"".equals(lbl_eposta.getText())) {
                JOptionPane.showMessageDialog(null, "Mail adresiniz hatalı. Lütfen düzeltiniz.", "Uyarı!", 0);
            }
            JOptionPane.showMessageDialog(null, "Lütfen tüm bilgileri eksiksiz doldurunuz.", "Bilgiler Eksik!", 0);
        }

    }//GEN-LAST:event_btn_kayitOlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kayitPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_gozat;
    private javax.swing.JButton btn_kayitOl;
    private javax.swing.JComboBox cmb_Gun;
    private javax.swing.JComboBox cmb_ay;
    private javax.swing.JComboBox cmb_ulke;
    private javax.swing.JComboBox cmb_yil;
    private javax.swing.ButtonGroup grpCinsiyet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_eposta;
    private javax.swing.JLabel lbl_resim;
    private javax.swing.JPasswordField pTxt_sifre;
    private javax.swing.JPasswordField pTxt_sifreOnayla;
    private javax.swing.JRadioButton rd_E;
    private javax.swing.JRadioButton rd_K;
    private javax.swing.JTextField txt_adi;
    private javax.swing.JTextField txt_ePosta;
    private javax.swing.JTextField txt_kullaniciAdi;
    private javax.swing.JTextField txt_soyadi;
    // End of variables declaration//GEN-END:variables
}
