/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package socialnetwork;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;

/**
 *
 * @author Fahrettin
 */
public class loginPanel extends javax.swing.JFrame {

    /**
     * Creates new form loginPanel
     */
    
    public loginPanel() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_kullaniciAdi = new javax.swing.JTextField();
        txt_sifre = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_Giris = new javax.swing.JButton();
        btn_KayitOl = new javax.swing.JButton();
        btn_SifremiUnuttum = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Social Network");
        setName("loginPanel"); // NOI18N
        setResizable(false);

        jLabel1.setText("Kullanıcı Adı/E-Posta");

        jLabel2.setText("Şifre");

        jLabel3.setText(":");

        jLabel4.setText(":");

        btn_Giris.setText("Giriş");
        btn_Giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GirisActionPerformed(evt);
            }
        });

        btn_KayitOl.setText("Kayıt Ol");
        btn_KayitOl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KayitOlActionPerformed(evt);
            }
        });

        btn_SifremiUnuttum.setText("Şifremi unuttum");
        btn_SifremiUnuttum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SifremiUnuttumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_kullaniciAdi, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(txt_sifre)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_SifremiUnuttum, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_KayitOl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Giris, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Giris, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_SifremiUnuttum, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_KayitOl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SifremiUnuttumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SifremiUnuttumActionPerformed
        // TODO add your handling code here:
        sifremiUnuttum sfr = new sifremiUnuttum();
        sfr.setVisible(true);

    }//GEN-LAST:event_btn_SifremiUnuttumActionPerformed

    private void btn_KayitOlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KayitOlActionPerformed
        // TODO add your handling code here:
        kayitPanel kyt = new kayitPanel();
        kyt.setVisible(true);
    }//GEN-LAST:event_btn_KayitOlActionPerformed
    static String kullaniciId;
    private void btn_GirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GirisActionPerformed
        // TODO add your handling code here:

        boolean mailmi = false;
        try {

            Connection c1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/socialnetworkdb?useSSL=false", "root", "5353");
            Statement s1 = c1.createStatement();
            

            

            EntityManagerFactory emf = Persistence.createEntityManagerFactory("socialNetworkPU");
            EntityManager em = emf.createEntityManager();

            for (int i = 0; i < txt_kullaniciAdi.getText().length(); i++) {
                if (txt_kullaniciAdi.getText().charAt(i) == '@') {
                    mailmi = true;
                }

            }
            Object kullaniciObj;
            Object singleResult;

            if (mailmi) {

                Query q = em.createQuery("select c.sifre from Kullanici c where c.eposta=:email");
                ResultSet rs = s1.executeQuery("SELECT id FROM kullanici where eposta='"+txt_kullaniciAdi.getText()+"'");
            rs.next();
            kullaniciId=rs.getString("id");
                q.setParameter("email", txt_kullaniciAdi.getText());
                
                singleResult = q.getSingleResult();
                

            } else {
                Query q = em.createQuery("select c.sifre from Kullanici c where c.eposta=:email");
                ResultSet rs = s1.executeQuery("SELECT id FROM kullanici where kullaniciadi='"+txt_kullaniciAdi.getText()+"'");
                rs.next();
                kullaniciId=rs.getString("id");
                System.out.println(kullaniciId);
                Query qk = em.createQuery("select c.sifre from Kullanici c where c.kullaniciPK.kullaniciadi=:kadi");
                qk.setParameter("kadi", txt_kullaniciAdi.getText());
                singleResult = qk.getSingleResult();
                System.out.println();

            }

            if (singleResult.toString() == null ? txt_sifre.getText() == null : singleResult.toString().equals(txt_sifre.getText())) {
                anaPencere ana = new anaPencere();
                ana.setVisible(true);
                super.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Şifrenizi yanlış girdiniz. Lütfen tekrar deneyiniz", "Hatalı Şifre", 0);
            }
            txt_sifre.setText("");
            em.close();
            emf.close();

        } catch (Exception e) {
            System.out.println(e);
            if (mailmi) {
                JOptionPane.showMessageDialog(null, "Girmiş olduğunuz e-Posta adresi sistemimizde kayıtlı değildir. Lütfen tekrar deneyiniz", "Kayıtsız e-Posta!", 0);
            } else {
                JOptionPane.showMessageDialog(null, "Girmiş olduğunuz kullanıcı adı sistemimizde kayıtlı değildir. Lütfen tekrar deneyiniz", "Kayıtsız kullanıcı adı!", 0);
            }
        }


    }//GEN-LAST:event_btn_GirisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginPanel.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginPanel.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginPanel.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginPanel.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new loginPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Giris;
    private javax.swing.JButton btn_KayitOl;
    private javax.swing.JButton btn_SifremiUnuttum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_kullaniciAdi;
    private javax.swing.JPasswordField txt_sifre;
    // End of variables declaration//GEN-END:variables
}
