/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package socialnetwork;

/**
 *
 * @author Fahrettin
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel(String a) {
        initComponents();
        jButton1.setText(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        lbl_ulke = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(300, 100));
        setLayout(null);

        jButton1.setText("jButton1");
        add(jButton1);
        jButton1.setBounds(12, 13, 79, 25);

        jToggleButton1.setText("Arkadaş Olma İsteği Gönder");
        add(jToggleButton1);
        jToggleButton1.setBounds(89, 70, 200, 20);

        lbl_ulke.setText("Ülke Adı:");
        add(lbl_ulke);
        lbl_ulke.setBounds(90, 40, 51, 16);

        jLabel1.setText("AD SOYAD");
        add(jLabel1);
        jLabel1.setBounds(90, 20, 157, 16);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbl_ulke;
    // End of variables declaration//GEN-END:variables
}
