/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package socialnetwork;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;

/**
 *
 * @author Fahrettin
 */
public class pnl_taniyor extends javax.swing.JPanel {

    String profilresmi;
    String adi;
    String soyadi;
    String ulkesi;
    int kullaniciid;
    int arkadasid;

    /**
     * Creates new form pnl_taniyor
     * @param ad
     * @param soyad
     * @param img
     * @param ulke
     * @param userid
     * @param eklenenID
     */
    public pnl_taniyor(String ad, String soyad, String img, String ulke,int userid,int eklenenID) {
        initComponents();
        adi=ad;
        soyadi=soyad;
        profilresmi=img;
        ulkesi=ulke;
        kullaniciid=userid;
        arkadasid=eklenenID;
    }

    public static void btnclick(int eklenen,int ekleyen) {
        Arkadas a = new Arkadas();
        long id = 1;//ilk kullanıcı için
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("socialNetworkPU");
        EntityManager em = emf.createEntityManager();
        Query qMaxId = em.createQuery("select MAX(c.id) from Arkadas c");
        id = Integer.parseInt(qMaxId.getSingleResult().toString()) + 1;
        a.setId(id);
        a.setEklenenid(eklenen);
        a.setKullaniciid(ekleyen);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_ulke = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setMinimumSize(new java.awt.Dimension(309, 130));
        setLayout(null);

        lbl_ulke.setText("Ülke Adı:");
        add(lbl_ulke);
        lbl_ulke.setBounds(90, 40, 51, 16);

        jLabel1.setText("AD SOYAD");
        add(jLabel1);
        jLabel1.setBounds(90, 20, 157, 16);

        jToggleButton1.setText("Arkadaş Olma İsteği Gönder");
        add(jToggleButton1);
        jToggleButton1.setBounds(89, 70, 200, 20);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbl_ulke;
    // End of variables declaration//GEN-END:variables
}
