/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package socialnetwork;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import static socialnetwork.kayitPanel.scaleImage;



/**
 *
 * @author Fahrettin
 */
public class Pnl_gonderiler extends javax.swing.JPanel {
String txtarea,adisoyadi,profilResmi,kullaniciAdi;
    
    public Pnl_gonderiler(String txt,String adi,String soyadi,String resim,String kAdi) {
        initComponents();
        txtarea=txt;
        adisoyadi=adi+" "+soyadi;
        profilResmi=resim;
        kullaniciAdi=kAdi;
        String url;
        if ("no-image.png".equals(profilResmi)) {
            url = "photos" + File.separator + "no-image.png";
        } else {
            url = "photos" + File.separator + kullaniciAdi + File.separator + profilResmi;
        }
        System.out.println(url);
        File fs = new File(url);
        BufferedImage bi = null;
        try {
            bi = ImageIO.read(fs);
        } catch (IOException ex) {
            Logger.getLogger(anaPencere.class.getName()).log(Level.SEVERE, null, ex);
        }
        ImageIcon icon = new ImageIcon(url);
        lbl_resim.setIcon(new ImageIcon(scaleImage(bi, BufferedImage.TYPE_INT_RGB, lbl_resim.getWidth(), lbl_resim.getHeight())));
        //RESİM EKLEME TAMAM

        lbl_adSoyad.setText(adisoyadi);
        jTextArea1.setText(txtarea);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextArea1 = new javax.swing.JTextArea();
        lbl_resim = new javax.swing.JLabel();
        lbl_adSoyad = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setPreferredSize(new java.awt.Dimension(538, 117));
        setLayout(null);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        add(jTextArea1);
        jTextArea1.setBounds(100, 40, 400, 64);

        lbl_resim.setText("jLabel2");
        add(lbl_resim);
        lbl_resim.setBounds(10, 10, 80, 80);

        lbl_adSoyad.setText("jLabel3");
        add(lbl_adSoyad);
        lbl_adSoyad.setBounds(120, 10, 160, 16);
    }// </editor-fold>//GEN-END:initComponents
boolean aktif = false;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_adSoyad;
    private javax.swing.JLabel lbl_resim;
    // End of variables declaration//GEN-END:variables
}
