/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package socialnetwork;



/**
 *
 * @author Fahrettin
 */
public class Pnl_durum extends javax.swing.JPanel {

    
    public Pnl_durum(String durum) {
        initComponents();
        jLabel1.setText(durum);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(300, 100));
        setLayout(null);

        jLabel1.setText("xzcjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj");
        add(jLabel1);
        jLabel1.setBounds(10, 40, 270, 16);
    }// </editor-fold>//GEN-END:initComponents
boolean aktif = false;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
