/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package socialnetwork;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static socialnetwork.kayitPanel.scaleImage;

/**
 *
 * @author Fahrettin
 */
public class Pnl_istekler extends javax.swing.JPanel {

    String profilresmi;
    String adi;
    String soyadi;
    String ulkesi;
    int kullaniciid;
    int arkadasid;
    String kullaniciAdi;
static long id;//ilk kullanıcı için
    /**
     * Creates new form NewJPanel
     *
     * @param ad
     * @param soyad
     * @param fUsername
     * @param img
     * @param ulke
     * @param eklenenID
     * @param userid
     */
    public Pnl_istekler(String ad, String soyad, String fUsername, String img, String ulke, int userid, int eklenenID) {
        initComponents();
        //jButton1.setText(a);
        adi = ad;
        soyadi = soyad;
        profilresmi = img;
        ulkesi = ulke;
        kullaniciid = userid;
        arkadasid = eklenenID;
        kullaniciAdi = fUsername;

        //-Resim
        String url;
        if ("no-image.png".equals(profilresmi)) {
            url = "photos" + File.separator + "no-image.png";
        } else {
            url = "photos" + File.separator + kullaniciAdi + File.separator + profilresmi;
        }
        System.out.println(url);
        File fs = new File(url);
        BufferedImage bi = null;
        try {
            bi = ImageIO.read(fs);
        } catch (IOException ex) {
            Logger.getLogger(anaPencere.class.getName()).log(Level.SEVERE, null, ex);
        }
        ImageIcon icon = new ImageIcon(url);
        lbl_resim.setIcon(new ImageIcon(scaleImage(bi, BufferedImage.TYPE_INT_RGB, lbl_resim.getWidth(), lbl_resim.getHeight())));
        //RESİM EKLEME TAMAM

        lbl_adSoyad.setText(adi + " " + soyadi);
        lbl_ulke.setText(ulkesi);

    }

    public void btnclickKabul() {
        Arkadas a = new Arkadas();
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("socialNetworkPU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery(" UPDATE Arkadas c SET c.kabul=TRUE WHERE c.kullaniciid=:id1 AND c.eklenenid=:id2");
q.setParameter("id1",kullaniciid);
q.setParameter("id2", arkadasid);
        em.getTransaction().begin();
q.executeUpdate();
        em.getTransaction().commit();
        em.close();
        emf.close();
        btn_kabul.setVisible(false);
        btn_reddet.setVisible(false);
        jLabel1.setText("Kabul edildi!");
        

    }

    public void btnclickSil() {
        Arkadas a = new Arkadas();
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("socialNetworkPU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("delete from Arkadas c where c.kullaniciid=:id1 AND c.eklenenid=:id2");
 Query q1 = em.createQuery("delete from Arkadas c where c.kullaniciid=:id1 AND c.eklenenid=:id2");
        q.setParameter("id1", kullaniciAdi);
        q.setParameter("id2", arkadasid);
          q1.setParameter("id1", arkadasid);
          q1.setParameter("id2", kullaniciAdi);
        em.getTransaction().begin();
q.executeUpdate();
q1.executeUpdate();
        em.getTransaction().commit();
        em.close();
        emf.close();
        btn_kabul.setVisible(false);
        btn_reddet.setVisible(false);
        jLabel1.setText("Reddedildi!");
    }

    Pnl_istekler(String ad, String soyad, String kullaniciAdi, String ulke, int kullaniciID, int kisiID) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_ulke = new javax.swing.JLabel();
        lbl_adSoyad = new javax.swing.JLabel();
        lbl_resim = new javax.swing.JLabel();
        btn_kabul = new javax.swing.JButton();
        btn_reddet = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(300, 100));
        setLayout(null);

        lbl_ulke.setText("Ülke Adı:");
        add(lbl_ulke);
        lbl_ulke.setBounds(90, 40, 51, 16);

        lbl_adSoyad.setText("AD SOYAD");
        add(lbl_adSoyad);
        lbl_adSoyad.setBounds(90, 10, 157, 16);

        lbl_resim.setBackground(new java.awt.Color(255, 255, 255));
        lbl_resim.setText("jLabel2");
        add(lbl_resim);
        lbl_resim.setBounds(10, 10, 70, 70);

        btn_kabul.setText("Kabul Et");
        btn_kabul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kabulActionPerformed(evt);
            }
        });
        add(btn_kabul);
        btn_kabul.setBounds(90, 70, 90, 25);

        btn_reddet.setText("Reddet");
        btn_reddet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reddetActionPerformed(evt);
            }
        });
        add(btn_reddet);
        btn_reddet.setBounds(199, 69, 80, 25);

        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(90, 70, 200, 16);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kabulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kabulActionPerformed
        // TODO add your handling code here:
        btnclickKabul();
    
    }//GEN-LAST:event_btn_kabulActionPerformed

    private void btn_reddetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reddetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_reddetActionPerformed
boolean aktif = false;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kabul;
    private javax.swing.JButton btn_reddet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_adSoyad;
    private javax.swing.JLabel lbl_resim;
    private javax.swing.JLabel lbl_ulke;
    // End of variables declaration//GEN-END:variables
}
