/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package socialnetwork;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author Fahrettin
 */
public class sifremiUnuttum extends javax.swing.JFrame {

    /**
     * Creates new form sifremiUnuttum
     */
    public sifremiUnuttum() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_MailSu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_SifreGonder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Şifremi Unuttum");
        setResizable(false);

        jLabel1.setText("Lütfen sistemimize kayıtlı oldugunuz e-mail adresini giriniz.");

        btn_SifreGonder.setText("Gönder");
        btn_SifreGonder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SifreGonderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(txt_MailSu, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btn_SifreGonder)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addComponent(txt_MailSu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_SifreGonder)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SifreGonderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SifreGonderActionPerformed
        // TODO add your handling code here:
        emailKontrol ek=new emailKontrol();
        if (ek.validate(txt_MailSu.getText())) {
            
        

        EntityManagerFactory emf = Persistence.createEntityManagerFactory("socialNetworkPU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select c.sifre from Kullanici c where c.eposta=:email");
        q.setParameter("email", txt_MailSu.getText());
            try {
                
            
        Object singleResult = q.getSingleResult();
        System.out.println(singleResult);
        
        em.close();
        emf.close();

        Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.socketFactory.port", "465");
        props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.port", "465");
        Session session = Session.getDefaultInstance(props,
                new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication("f.yilmazproject@gmail.com", "ylmz5353");
                    }
                });
        try {
            Message message=new MimeMessage(session);
            message.setFrom(new InternetAddress(null, "f-yilmaz's socialNetwork"));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(txt_MailSu.getText()));
            message.setSubject("Şifre Hatırlatma!");
            message.setText(singleResult.toString());
            Transport.send(message);
            JOptionPane.showMessageDialog(null, "Şifre başarıyla gönderildi.");
            super.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
            txt_MailSu.setText("");
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Girmiş olduğunuz mail adresi sistemimizde kayıtlı değildir.Lütfen tekrar deneyiniz.", "Uyarı!", 0);
                System.out.println(e);
                txt_MailSu.setText("");
            }
        }
        else JOptionPane.showMessageDialog(null, "Mail adresiniz hatalı. Lütfen düzeltiniz.", "Uyarı!", 0);
        txt_MailSu.setText("");
        
    }//GEN-LAST:event_btn_SifreGonderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sifremiUnuttum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sifremiUnuttum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sifremiUnuttum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sifremiUnuttum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sifremiUnuttum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_SifreGonder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt_MailSu;
    // End of variables declaration//GEN-END:variables
}
